### PR TITLE
Committee Photos

### PR DESCRIPTION
**Pull request by BenWoodford76**
Add Photos for 2019-20 Committee

### CODE REVIEW

**Comment by samozzy** [comment]
@BenWoodford76 - Good to go? Not everyone's got a rollover but it works :stuck_out_tongue:

**Comment by BenWoodford76** [comment]
Sam, shall i merge this now then can work on making main photos B&W tomorrow?

**Comment by samozzy** [comment]
@BenWoodford76 All photos should be B&W, turns out smugmug has some handy in built editing features

**Comment by BenWoodford76** [comment]
@samozzy Fabulous, feel free to merge

**Pull request merged**
