### PR TITLE
Partial update to committee list

### PR DESCRIPTION
**Pull request by jb3**

### CODE REVIEW

**Comment by jb3** [comment]
:shipit:

**Comment by samozzy** [comment]
@jb3 Can you update this to add notes of "until X 2023" and "from X 2023" where X is a month please?
(Unless it's like September in which case we'll just ignore)

**Comment by jb3** [comment]
After conversing with Ellie (who will be adding the rest of roles to this PR with me later on), roles no longer held are shown on the History site once that gets updated, this page should reflect the current committee for contact point purposes.

I'll go through this file with Ellie to fill in the rest of the role updates, a history PR can be made later anytime to add the full committe history but I think only the current positions should be reflected here.

**Comment by samozzy** [comment]
@jb3 You're so right, reading this when I'm not half asleep would be ideal - all yours.

**Review by samozzy — APPROVED** [review]

**Pull request merged**
