### PR TITLE
Update committee.yml

### PR DESCRIPTION
**Pull request by LHagen-nnt**
2024 committee update

### CODE REVIEW

**Review by jb3 — APPROVED** [review]

**Comment by jb3** [comment]
@samozzy are you able to merge? CI has failed but not sure if it's an actual fail or spurious CI (à la TEC RIGS CI)

**Comment by samozzy** [comment]
@jb3 @jb3 Enjoy!

**Comment by jb3** [comment]
Thanks for the merge :) CI seems to have failed with some HTML test error, which is peculiar since I don't think these PRs would've amended that?

**Comment by samozzy** [comment]
Correct; htmltest checks all the links whenever it's run, not assuming that a link that once worked still does! I'll see to those now and that should update everything.

**Comment by samozzy** [comment]
Correct; htmltest checks all the links whenever it's run, not assuming that a link that once worked still does! I'll see to those now and that should update everything.

**Pull request merged**
